

#         Powered by TabooLib 6.0         #


options:
  check-update: true
database:
  type: SQLite
  source:
    mysql:
      host: localhost
      port: 3306
      user: root
      password: root
      database: minecraft
loader:
  packs-files:
    - ''